# ═══════════════════════════════════════════════════════════════════
#   ✦  L U M E N   B O O K   R E A D E R  ✦
#
#   Created by  Angela López Mendoza   ·   @angelahack1
#   Developer · Architect · Creator of Lumen
# ═══════════════════════════════════════════════════════════════════
"""Single source of truth for Lumen's version — runtime AND build time.

Git tags are the source of truth, ``_version.py`` is generated at build time
and read at runtime, and this same module renders the Win32 ``VERSIONINFO``
resource that PyInstaller embeds into every ``.exe`` we ship.  Because one
module answers every question, the version in the installer's header badge,
the ``Uninstaller.exe`` properties sheet, the "Installed apps" entry and the
running reader can never drift apart.

Resolution order (highest priority first)
-----------------------------------------
  1. ``lumen_reader/_version.py``       - generated by ``build.py`` (gitignored)
  2. ``$LUMEN_VERSION``                 - exported by a previous build step
  3. ``git describe --tags``            - the most recent reachable ``v*`` tag
  4. ``pyproject.toml``                 - the declared fallback
  5. ``0.0.0+unknown``                  - sentinel; never raises

See ``RELEASING.md`` for the full contract.
"""

from __future__ import annotations

import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Tuple

UNKNOWN_VERSION = "0.0.0+unknown"
ENV_VAR_NAME = "LUMEN_VERSION"

# SemVer 2.0.0 - semver.org's officially recommended regular expression.
_SEMVER_RE = re.compile(
    r"^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)"
    r"(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)"
    r"(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?"
    r"(?:\+(?P<build>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
)

_PACKAGE_ROOT = Path(__file__).resolve().parent
_REPO_ROOT = _PACKAGE_ROOT.parent

# Resolving the version shells out to git, so memoise it. A reader that opens a
# hundred books must not pay for a hundred `git describe` calls.
_CACHED_VERSION: Optional[str] = None


# ── Layer 1: the generated module ──────────────────────────────────────────

def _read_generated_module() -> Optional[str]:
    """Return ``__version__`` from the build-generated ``_version.py``."""
    try:
        from . import _version  # type: ignore[attr-defined]
    except Exception:
        return None
    value = str(getattr(_version, "__version__", "") or "")
    return value.strip() or None


# ── Layer 3: git ───────────────────────────────────────────────────────────

def _repo_root_candidates() -> list[Path]:
    """Directories that might hold the ``.git`` we should ask."""
    return [_REPO_ROOT, _PACKAGE_ROOT, Path.cwd()]


def _run_git(args: list[str], cwd: Path) -> Optional[str]:
    """Run ``git <args>`` in *cwd*; return stripped stdout or ``None``."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return None
    if result.returncode != 0:
        return None
    out = (result.stdout or "").strip()
    return out or None


def derive_version_from_git(cwd: Optional[Path] = None) -> Optional[str]:
    """Derive a version from the local git tree.

    Always returns the **bare base tag** - no ``.devN`` distance, no ``+gSHA``
    local part, no ``.dirty`` marker - so the public version always reads as a
    clean SemVer (``"1.2.3"``).

      * ``"1.2.3"`` - most recent reachable ``v*`` tag
      * ``"0.0.0"`` - a git repo with no ``v*`` tags yet
      * ``None``    - not a git repo, or git is not installed
    """
    candidates = [cwd] if cwd is not None else _repo_root_candidates()
    for repo in candidates:
        if repo is None:
            continue
        if not (repo / ".git").exists() and _run_git(["rev-parse", "--git-dir"], repo) is None:
            continue
        described = _run_git(
            ["describe", "--tags", "--abbrev=0", "--match", "v[0-9]*"], repo
        )
        if described:
            return described[1:] if described.startswith("v") else described
        return "0.0.0"
    return None


def git_commit(cwd: Optional[Path] = None) -> str:
    """Short commit hash of HEAD, or ``"unknown"``."""
    for repo in ([cwd] if cwd is not None else _repo_root_candidates()):
        if repo is None:
            continue
        sha = _run_git(["rev-parse", "--short=12", "HEAD"], repo)
        if sha:
            return sha
    return "unknown"


# ── Layer 4: the declared fallback ─────────────────────────────────────────

def declared_version() -> Optional[str]:
    """Read the version declared in ``pyproject.toml``.

    This is the floor, not the ceiling: a release build derives its version
    from a git tag.  The fallback exists so a source checkout with no tags -
    a zip download, a fresh fork - still reports something honest, and so the
    build scripts can WARN when the tags have fallen behind ``pyproject.toml``
    instead of silently shipping a stale number.
    """
    pyproject = _REPO_ROOT / "pyproject.toml"
    if not pyproject.is_file():
        return None
    try:
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover - Python < 3.11
        return None
    try:
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    except Exception:
        return None
    value = str(data.get("project", {}).get("version", "") or "").strip()
    return value or None


# ── Public API ─────────────────────────────────────────────────────────────

def get_version() -> str:
    """Return the running version. Always a non-empty string; never raises."""
    global _CACHED_VERSION
    if _CACHED_VERSION is not None:
        return _CACHED_VERSION
    resolved = (
        _read_generated_module()
        or (os.environ.get(ENV_VAR_NAME, "").strip() or None)
        or derive_version_from_git()
        or declared_version()
        or UNKNOWN_VERSION
    )
    # A tagless git checkout answers "0.0.0"; prefer the declared version over
    # that placeholder so a fresh clone still shows a real number.
    if resolved == "0.0.0":
        resolved = declared_version() or resolved
    _CACHED_VERSION = resolved
    return resolved


def get_version_info() -> dict:
    """Structured version metadata for About boxes and diagnostics."""
    version = get_version()
    parsed = parse_semver(public_version(version)) or {}
    try:
        from . import _version  # type: ignore[attr-defined]
        commit = str(getattr(_version, "__commit__", "") or "") or "unknown"
        date = str(getattr(_version, "__date__", "") or "")
        build = str(getattr(_version, "__build__", "") or "") or version
    except Exception:
        commit, date, build = git_commit(), "", version
    return {
        "version": version,
        "public": public_version(version),
        "build": build,
        "commit": commit,
        "date": date,
        "major": parsed.get("major", 0),
        "minor": parsed.get("minor", 0),
        "patch": parsed.get("patch", 0),
        "prerelease": parsed.get("prerelease", ""),
    }


def public_version(build_string: str) -> str:
    """Strip a SemVer build-metadata local part (``+anything``)."""
    return build_string.split("+", 1)[0] if "+" in build_string else build_string


def parse_semver(version: str) -> Optional[dict]:
    """Parse a SemVer 2.0.0 string; ``None`` when it does not match."""
    m = _SEMVER_RE.match(version or "")
    if not m:
        return None
    g = m.groupdict()
    return {
        "major": int(g["major"]),
        "minor": int(g["minor"]),
        "patch": int(g["patch"]),
        "prerelease": g.get("prerelease") or "",
        "build": g.get("build") or "",
    }


def semver_to_win32_tuple(version: str) -> Tuple[int, int, int, int]:
    """Convert SemVer to the ``VS_FIXEDFILEINFO`` (MAJOR, MINOR, PATCH, BUILD)
    4-tuple.  BUILD is hard-coded to ``0`` because SemVer's ``+build`` metadata
    is explicitly non-comparable per spec."""
    parsed = parse_semver(public_version(version))
    if parsed is None:
        return (0, 0, 0, 0)
    return (parsed["major"], parsed["minor"], parsed["patch"], 0)


def bump(version: str, part: str) -> str:
    """Return the next ``major`` / ``minor`` / ``patch`` version.

    Powers ``build_complete_release.py --bump minor``, so "every minor and
    every major" is one command instead of a hand-typed tag.  Forward-only: it
    computes a NEW version, it never rewrites an existing one.
    """
    parsed = parse_semver(public_version(version))
    if parsed is None:
        raise ValueError(f"cannot bump a non-SemVer version: {version!r}")
    major, minor, patch = parsed["major"], parsed["minor"], parsed["patch"]
    part = (part or "").lower().strip()
    if part == "major":
        return f"{major + 1}.0.0"
    if part == "minor":
        return f"{major}.{minor + 1}.0"
    if part == "patch":
        return f"{major}.{minor}.{patch + 1}"
    raise ValueError(f"unknown bump part {part!r} (expected major/minor/patch)")


def compare(left: str, right: str) -> int:
    """Compare two SemVer strings: -1, 0 or 1 (pre-release ranks below release)."""
    lp = parse_semver(public_version(left)) or {"major": 0, "minor": 0, "patch": 0, "prerelease": ""}
    rp = parse_semver(public_version(right)) or {"major": 0, "minor": 0, "patch": 0, "prerelease": ""}
    lkey = (lp["major"], lp["minor"], lp["patch"])
    rkey = (rp["major"], rp["minor"], rp["patch"])
    if lkey != rkey:
        return -1 if lkey < rkey else 1
    lpre, rpre = lp["prerelease"], rp["prerelease"]
    if lpre == rpre:
        return 0
    if not lpre:
        return 1        # 1.0.0 > 1.0.0-rc1
    if not rpre:
        return -1
    return -1 if lpre < rpre else 1


# ── Build-time helpers (called by build.py and its siblings) ───────────────

def write_version_module(
    target_path: Path,
    version: str,
    build: Optional[str] = None,
    commit: str = "unknown",
    date: str = "",
) -> None:
    """Write the generated ``lumen_reader/_version.py`` read at runtime."""
    target_path = Path(target_path)
    target_path.parent.mkdir(parents=True, exist_ok=True)
    if build is None:
        build = version
    if not date:
        date = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    target_path.write_text(
        '"""Generated by build.py - DO NOT EDIT BY HAND.\n'
        "\n"
        "This file is regenerated on every build and is gitignored.\n"
        "Source of truth: git tags. See RELEASING.md.\n"
        '"""\n'
        f"__version__ = {version!r}\n"
        f"__build__   = {build!r}\n"
        f"__commit__  = {commit!r}\n"
        f"__date__    = {date!r}\n",
        encoding="utf-8",
    )


COMPANY_NAME = "XAIHT"
AUTHOR = "Angela López Mendoza"
COPYRIGHT = "Copyright (c) 2026 Angela López Mendoza · XAIHT. MIT License."
PRODUCT_NAME = "Lumen Book Reader"
ABOUT_URL = "https://github.com/XAIHT/Lumen-Book-Reader"


def render_pyinstaller_version_file(
    version: str,
    *,
    product_name: str = PRODUCT_NAME,
    company_name: str = COMPANY_NAME,
    file_description: str = "Lumen Book Reader — created by Angela López Mendoza (XAIHT)",
    internal_name: str = "Lumen",
    original_filename: str = "Lumen.exe",
    legal_copyright: str = COPYRIGHT,
    author: str = AUTHOR,
) -> str:
    """Return the contents of a PyInstaller ``--version-file``.

    Windows reads ``ProductVersion`` out of this resource, which is exactly how
    ``install.py`` / ``uninstall.py`` learn their own version when frozen - so
    the GUI badge and the Explorer properties sheet are the same string by
    construction, not by convention.
    """
    filevers = semver_to_win32_tuple(version)
    public = public_version(version)
    return f"""# UTF-8
#
# Win32 VERSIONINFO resource generated by Lumen's build scripts.
# Do not edit by hand - regenerate via ``python build.py [--version X.Y.Z]``.
#
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers},
    prodvers={filevers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName',      u'{company_name}'),
            StringStruct(u'Author',           u'{author}'),
            StringStruct(u'Creator',          u'{author}'),
            StringStruct(u'FileDescription',  u'{file_description}'),
            StringStruct(u'FileVersion',      u'{public}'),
            StringStruct(u'InternalName',     u'{internal_name}'),
            StringStruct(u'LegalCopyright',   u'{legal_copyright}'),
            StringStruct(u'OriginalFilename', u'{original_filename}'),
            StringStruct(u'ProductName',      u'{product_name}'),
            StringStruct(u'ProductVersion',   u'{version}'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


__all__ = [
    "ABOUT_URL",
    "AUTHOR",
    "COMPANY_NAME",
    "COPYRIGHT",
    "ENV_VAR_NAME",
    "PRODUCT_NAME",
    "UNKNOWN_VERSION",
    "bump",
    "compare",
    "declared_version",
    "derive_version_from_git",
    "get_version",
    "get_version_info",
    "git_commit",
    "parse_semver",
    "public_version",
    "render_pyinstaller_version_file",
    "semver_to_win32_tuple",
    "write_version_module",
]
